apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-config
  namespace: microservices
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  SERVICE_NAME: "oeson-capstone-microservice"