apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: microservices
spec:
  selector:
    app: microservice
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort